### ISSUE TITLE
Add support for Mule 3.6.1

### ISSUE THREAD

**Issue by magnus-larsson** [soi-toolkit/soi-toolkit-mule#1]

**Comment by hdahl** [comment]
This issue was moved to hdahl/st2-mig-issues_tmp_holder_repo#1

**Comment by hdahl** [comment]
This issue was moved to hdahl/st2-mig-issues_tmp_holder_repo#2

**Comment by magnus-larsson** [comment]
Close this one, the remaining work to support Mule 3.6.1, upgrade to Log4j v2, is handles by a separate issue, see #386.
