### ISSUE TITLE
Support log4j v2 for Mule 3.6 or later

### ISSUE THREAD

**Issue by magnus-larsson** [soi-toolkit/soi-toolkit-mule#386]
# Background information

Remaining issue from #1...

1. Mulesoft blog om Log4j 2 i Mule 3.6 - http://blogs.mulesoft.org/mule-3-6-asynchronous-logging/
1. InfoQ - Apache Log4j 2.0 - Worth the Upgrade? - http://www.infoq.com/news/2014/07/apache-log4j2
1. Apache doc - Asynchronous Loggers for Low-Latency Logging - http://logging.apache.org/log4j/2.x/manual/async.html
1. Apache doc - Migrating from Log4j 1.x - https://logging.apache.org/log4j/2.x/manual/migration.html

# What needs to be done

1. Cleanup the classpath to avoid that log4j v1 by misstake is used during development. Ensure that we only use slf4j 1.7.7 (part of mule 3.6.1) when we develop for mule 3.6.

1. How to utilise the concept of log4j2.xml and log4j2-test.xml as described in the mulesoft-blog above?
Can we replace our homegrown solution for log4j v1 with a standard feature based on this?
  
1. Adopt the generators.

**Comment by hdahl** [comment]
Blocked by #387, projekt doesn't build.

**Comment by hdahl** [comment]
Released in 2.0.0-M5
