### ISSUE TITLE
Remove all references to codehaus maven repository

### ISSUE THREAD

**Issue by hdahl** [soi-toolkit/soi-toolkit-mule#387]
Codehaus has been discontinued (from May 17 2015).
Maven repo mirrored to central so should be fine just to remove repo-refs from pom-files.

http://www.codehaus.org
http://www.infoq.com/news/2015/03/codehaus-google-code

---
Update: removing the repo-ref wasn't enough, some dependencies can't be resolved, for example:
org.mule.modules:mule-module-xml:jar:3.5.0 -> net.java.dev.stax-utils:stax-utils:jar:20080702
Adding a repo-ref to:
https://repository.mulesoft.org/nexus/content/repositories/public/
seems to resolve all problems so far.

**Comment by martin-flower** [comment]
<repositories>
     <repository>
      <id>maven2-repository.dev.java.net</id>
      <url>http://download.java.net/maven/2/</url>
      <layout>default</layout>
    </repository>

    <repository>
     <id>mulesoft</id>
     <name>MuleSoft Repository</name>
     <url>https://repository.mulesoft.org/nexus/content/repositories/releases</url>
    </repository>
        
    
    <repository>
     <id>mule</id>
     <name>Mule Dependencies</name>
     <url>http://dist.codehaus.org/mule/dependencies/maven2</url>
     <snapshots>
      <enabled>false</enabled>
     </snapshots>
    </repository>
   <repositories>

**Comment by martin-flower** [comment]
jug.osgi - artifact missing - NPÖAdapter, AgP (Jenkins) https://skl-tp.atlassian.net/browse/PAN-116

**Comment by martin-flower** [comment]
jug.osgi does not exist on maven central, or download.java.net/maven/2/
